version: 2
jobs:
  build:
    docker:
      - image: nontan18/texlive
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk update
            apk add make curl
      - run:
          name: Build PDF
          command: make all
      - run:
          name: Upload
          command: ../tools/up2discord.sh
